version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-volume:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password1234
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=m437-tickets.westeurope.cloudapp.azure.com
      - GF_SMTP_ENABLED=false
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
    links:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
     - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password1234
    ports:
     - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  grafana-volume:
  mysql-data:
